import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../lib/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  //TODO global loggedIn state storing user data

  return (
    <html lang="en">
    
  

    
      <body className={inter.className}>
        <div>
          <h1>1</h1>
          {children}</div>
        {<Navbar></Navbar>}
      </body>
    </html>
  )
}
